"""Add active_connections field to metrics

Revision ID: 2f584dc0d9f2
Revises: e1a7c4cc82bb
Create Date: 2026-04-13 03:16:07.907583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f584dc0d9f2'
down_revision: Union[str, None] = 'e1a7c4cc82bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metric_snapshots', sa.Column('active_connections', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('metric_snapshots', 'active_connections')
    # ### end Alembic commands ###
