"""Add new metric fields (disk read/write bytes, process count)

Revision ID: e1a7c4cc82bb
Revises: a9fa3330d961
Create Date: 2026-04-13 03:15:47.628687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1a7c4cc82bb'
down_revision: Union[str, None] = 'a9fa3330d961'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metric_snapshots', sa.Column('disk_read_bytes', sa.Float(), nullable=True))
    op.add_column('metric_snapshots', sa.Column('disk_write_bytes', sa.Float(), nullable=True))
    op.add_column('metric_snapshots', sa.Column('process_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('metric_snapshots', 'process_count')
    op.drop_column('metric_snapshots', 'disk_write_bytes')
    op.drop_column('metric_snapshots', 'disk_read_bytes')
    # ### end Alembic commands ###
